# Generated by Django 2.2.4 on 2019-08-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Mission'),
        ),
    ]
