# Generated by Django 2.2.4 on 2019-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190829_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3)),
                ('manitoFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
