# Generated by Django 2.2.4 on 2019-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190829_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='managerFlag',
            field=models.BooleanField(default=False),
        ),
    ]
