# Generated by Django 2.2.4 on 2019-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_managerflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
