# Generated by Django 2.2.4 on 2019-08-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mission_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Mission'),
        ),
    ]
